version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["typescript"]
  environment = ["nodejs"]
  dialect = "typescript"

[[exclude_patterns]]
pattern = "node_modules/**"

[[exclude_patterns]]
pattern = "dist/**"

[[exclude_patterns]]
pattern = "static/**"

[[exclude_patterns]]
pattern = ".sanity/**"

# Trigger DeepSource re-analysis
